"""Project models and ZIP-backed persistence for Prism."""

from prism.project.archive import (
    MANIFEST_MEMBER,
    PROJECT_SUFFIX,
    create_project,
    import_audio,
    load_project,
    migrate_project,
    save_project,
    validate_project,
)
from prism.project.errors import (
    AssetImportError,
    ExternalProjectChangeError,
    InvalidArchiveError,
    InvalidProjectError,
    MigrationError,
    ProjectArchiveError,
    ProjectLockedError,
    ProjectResourceLimitError,
    ProjectValidationError,
    StagedUploadError,
    UnsupportedSchemaVersionError,
    WorkingProjectError,
)
from prism.project.models import (
    AssetReference,
    AudioClip,
    ClipSlot,
    MixerState,
    PluginInstance,
    PluginStateReference,
    Project,
    ProjectRevision,
    Scene,
    Track,
    TransportState,
    new_project,
)
from prism.project.repository import (
    WORKING_FORMAT_VERSION,
    WORKING_SUFFIX,
    ProjectRepository,
    RepositoryLimits,
    RepositorySnapshot,
    SourceFingerprint,
    StagedAudioUpload,
    open_repository,
    working_path_for_archive,
)
from prism.project.validation import LayeredValidationReport, ValidationStage

__all__ = [
    "AssetImportError",
    "AssetReference",
    "AudioClip",
    "ClipSlot",
    "ExternalProjectChangeError",
    "InvalidArchiveError",
    "InvalidProjectError",
    "LayeredValidationReport",
    "MANIFEST_MEMBER",
    "MigrationError",
    "MixerState",
    "PluginInstance",
    "PluginStateReference",
    "PROJECT_SUFFIX",
    "Project",
    "ProjectArchiveError",
    "ProjectLockedError",
    "ProjectRepository",
    "ProjectResourceLimitError",
    "ProjectRevision",
    "ProjectValidationError",
    "RepositoryLimits",
    "RepositorySnapshot",
    "Scene",
    "SourceFingerprint",
    "StagedAudioUpload",
    "StagedUploadError",
    "Track",
    "TransportState",
    "UnsupportedSchemaVersionError",
    "ValidationStage",
    "WORKING_FORMAT_VERSION",
    "WORKING_SUFFIX",
    "WorkingProjectError",
    "create_project",
    "import_audio",
    "load_project",
    "migrate_project",
    "new_project",
    "open_repository",
    "save_project",
    "validate_project",
    "working_path_for_archive",
]
